export const latestRecipe = [
  {
    name: 'Creamy Avocado Pasta',
    chef: 'Chef Ama',
    munites: '25',
    badge: 'vegetarian',
    image: 'https://via.placeholder.com/300x200.png?text=Avocado+Pasta',
  },
  {
    name: 'Spicy Jollof Rice',
    chef: 'Chef Kwame',
    munites: '45',
    badge: 'vegetarian',
    image: 'https://via.placeholder.com/300x200.png?text=Jollof+Rice',
  },
  {
    name: 'Grilled Plantain Salad',
    chef: 'Chef Esi',
    munites: '20',
    badge: 'vegetarian',
    image: 'https://via.placeholder.com/300x200.png?text=Plantain+Salad',
  },
  {
    name: 'Mango Coconut Smoothie',
    chef: 'Chef Kojo',
    munites: '10',
    badge: 'vegetarian',
    image: 'https://via.placeholder.com/300x200.png?text=Mango+Smoothie',
  },
  {
    name: 'Ginger Carrot Soup',
    chef: 'Chef Abena',
    munites: '30',
    badge: 'vegetarian',
    image: 'https://via.placeholder.com/300x200.png?text=Carrot+Soup',
  },
  {
    name: 'Fried Rice with Tofu',
    chef: 'Chef Nana',
    munites: '35',
    badge: 'vegetarian',
    image: 'https://via.placeholder.com/300x200.png?text=Tofu+Rice',
  },
  {
    name: 'Okra Stew Delight',
    chef: 'Chef Selorm',
    munites: '40',
    badge: 'vegetarian',
    image: 'https://via.placeholder.com/300x200.png?text=Okra+Stew',
  },
  {
    name: 'Papaya Fruit Bowl',
    chef: 'Chef Adwoa',
    munites: '15',
    badge: 'vegetarian',
    image: 'https://via.placeholder.com/300x200.png?text=Papaya+Bowl',
  },
  {
    name: 'Coconut Bean Curry',
    chef: 'Chef Yaw',
    munites: '50',
    badge: 'vegetarian',
    image: 'https://via.placeholder.com/300x200.png?text=Bean+Curry',
  },
]
