export const latestRecipe = [
  {
    name: 'Creamy Avocado Pasta',
    chef: 'Chef Ama',
    minutes: 25,
    badge: 'vegetarian',
    image: 'https://via.placeholder.com/300x200.png?text=Avocado+Pasta',
  },
  {
    name: 'Spicy Jollof Rice',
    chef: 'Chef Kwame',
    minutes: 45,
    badge: 'vegetarian',
    image: 'https://via.placeholder.com/300x200.png?text=Jollof+Rice',
  },
  {
    name: 'Grilled Plantain Salad',
    chef: 'Chef Esi',
    minutes: 20,
    badge: 'vegetarian',
    image: 'https://via.placeholder.com/300x200.png?text=Plantain+Salad',
  },
  {
    name: 'Mango Coconut Smoothie',
    chef: 'Chef Kojo',
    minutes: 10,
    badge: 'vegetarian',
    image: 'https://via.placeholder.com/300x200.png?text=Mango+Smoothie',
  },
  {
    name: 'Ginger Carrot Soup',
    chef: 'Chef Abena',
    minutes: 30,
    badge: 'vegetarian',
    image: 'https://via.placeholder.com/300x200.png?text=Carrot+Soup',
  },
  {
    name: 'Fried Rice with Tofu',
    chef: 'Chef Nana',
    minutes: 35,
    badge: 'vegetarian',
    image: 'https://via.placeholder.com/300x200.png?text=Tofu+Rice',
  },
  {
    name: 'Okra Stew Delight',
    chef: 'Chef Selorm',
    minutes: 40,
    badge: 'vegetarian',
    image: 'https://via.placeholder.com/300x200.png?text=Okra+Stew',
  },
  {
    name: 'Papaya Fruit Bowl',
    chef: 'Chef Adwoa',
    minutes: 15,
    badge: 'vegetarian',
    image: 'https://via.placeholder.com/300x200.png?text=Papaya+Bowl',
  },
  {
    name: 'Coconut Bean Curry',
    chef: 'Chef Yaw',
    minutes: 50,
    badge: 'vegetarian',
    image: 'https://via.placeholder.com/300x200.png?text=Bean+Curry',
  },
]
