export const latestRecipe = [
  {
    name: 'Creamy Avocado Pasta',
    chef: 'Chef Ama',
    minutes: 25,
    badge: 'vegetarian',
    image: '/latestRcp.png',
  },
  {
    name: 'Spicy Jollof Rice',
    chef: 'Chef Kwame',
    minutes: 45,
    badge: 'vegetarian',
    image: '/latestRcp.png',
  },
  {
    name: 'Grilled Plantain Salad',
    chef: 'Chef Esi',
    minutes: 20,
    badge: 'vegetarian',
    image: '/latestRcp.png',
  },
  {
    name: 'Mango Coconut Smoothie',
    chef: 'Chef Kojo',
    minutes: 10,
    badge: 'vegetarian',
    image: '/latestRcp.png',
  },
  {
    name: 'Ginger Carrot Soup',
    chef: 'Chef Abena',
    minutes: 30,
    badge: 'vegetarian',
    image: '/latestRcp.png',
  },
  {
    name: 'Fried Rice with Tofu',
    chef: 'Chef Nana',
    minutes: 35,
    badge: 'vegetarian',
    image: '/latestRcp.png',
  },
  {
    name: 'Okra Stew Delight',
    chef: 'Chef Selorm',
    minutes: 40,
    badge: 'vegetarian',
    image: '/latestRcp.png',
  },
  {
    name: 'Papaya Fruit Bowl',
    chef: 'Chef Adwoa',
    minutes: 15,
    badge: 'vegetarian',
    image: '/latestRcp.png',
  },
  {
    name: 'Coconut Bean Curry',
    chef: 'Chef Yaw',
    minutes: 50,
    badge: 'vegetarian',
    image: '/latestRcp.png',
  },
]
